### ISSUE TITLE
Install fails on Bullseye, erlang repository doesn't support Bullseye (yet)

### ISSUE THREAD

**Issue by alexAubin** [YunoHost-Apps/mobilizon_ynh#104]
`E: The repository 'http://packages.erlang-solutions.com/debian bullseye Release' does not have a Release file.`

Maybe they'll add it in the future though, I suppose

Though the best way to fix this would be to not even depend on the extra repo (c.f. https://github.com/YunoHost-Apps/mobilizon_ynh/issues/90 )

**Comment by yalh76** [comment]
Fixed with ugly workaround https://github.com/YunoHost-Apps/mobilizon_ynh/blob/b63c7833f80de56bbc4a255ddda3b865a5637afc/scripts/install#L82-L88
