### ISSUE TITLE
After Installation: "Mobilizon server seems to be temporarily down"  ???

### ISSUE THREAD

**Issue by rocky-III** [YunoHost-Apps/mobilizon_ynh#106]
Installation was successful but when i go to the domain I installed mobilizon I just get this:

> 
> We're sorry, but something went wrong on our end.
> The Mobilizon server Mobilizon seems to be temporarily down.
> If the issue persists, you may try to contact the server administrator.

What can i try? Thanks for help

**Comment by yalh76** [comment]
you should look at the logs or provide a yunopaste of the install logs
