### ISSUE TITLE
Can't upgrade

### ISSUE THREAD

**Issue by stemy2** [YunoHost-Apps/mobilizon_ynh#115]
### Describe the bug

*Upgrade fails at every attempt*

### Context

- Hardware: *Desktop PC*
- YunoHost version: 4.2.8.1
- I have access to my server: *Full*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *yes*
  - If yes, please explain: Background script to prevent regular wiping of resolv.dnsmasq.conf.
- Using, or trying to install package version/branch: master
- If upgrading, current package version: *1.2.2*

### Steps to reproduce
    ```sh
    sudo yunohost app upgrade
    ```

### Expected behavior

*Upgrade succeed*

### Logs

https://paste.yunohost.org/raw/uzutitutuv

**Comment by yalh76** [comment]
The upgrade failed because mobilizon can't be upgrade because the file `/etc/systemd/system/mobilizon.service` doesn't exist, can you check why ? and where is your `mobilizon.service`

**Comment by stemy2** [comment]
How can i have a such information ? I have no idea since i never faced to a such problem.

**Comment by yalh76** [comment]
You have to log using ssh, and for example go to `/etc/systemd/system/` to check if the file exists
Or you can do `nano /etc/systemd/system/mobilizon.service`

**Comment by stemy2** [comment]
The app had no content, so i tried a reinstallation. But installation desn't work either.

https://paste.yunohost.org/raw/odarelanof

**Comment by yalh76** [comment]
The install failed caused by a timeout,:
`2021-08-31 17:02:11,331: DEBUG - ** (Mix) Package fetch failed and no cached copy available (https://repo.hex.pm/tarballs/absinthe-1.6.5.tar)`

You can retry

**Comment by stemy2** [comment]
I retryed countless times, but it still fails.

**Comment by yalh76** [comment]
Maybe something specific to your installation.... as package_check works
