### ISSUE TITLE
JavaScript heap out of memory

### ISSUE THREAD

**Issue by clawfire** [YunoHost-Apps/mobilizon_ynh#118]
### Describe the bug

When trying to install mobilizon on my instance, at the node part (building) I got a out of memory for Javascript error.

### Context

- Hardware: *VPS bought online*
- YunoHost version: *4.2.8.3*
- I have access to my server: *Through SSH*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*

### Steps to reproduce

- search for mobilizon
- launch install

### Expected behavior

Installation going smoothly

### Logs

https://paste.yunohost.org/raw/bimuwewonu

**Comment by 0cwa** [comment]
Same issue on VPS 4.3.5; adding 2gb swap didn't help
