### ISSUE TITLE
the user mobilizon_notifs is integrated on Nextcloud, how remove it ?

### ISSUE THREAD

**Issue by rodinux** [YunoHost-Apps/mobilizon_ynh#120]
### Describe the bug

*the app create a user mobilizon_notifs*, this user have an account with ldap on Nextcloud app, and it create trouble*

### Context

- Hardware: *Public Cloud bought online *
- YunoHost version: 4.3.4.1
- I have access to my server: *Through SSH | through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*

- Using, or trying to install package version/branch: stable 1.3.2~ynh1

### Steps to reproduce

I had to repair the files in Nextcloud with this command

 ```sh
# sudo -u nextcloud php occ files:scan --all
```
```
Starting scan for user 1 out of 6 (user1)
Starting scan for user 2 out of 6 (user2)
Starting scan for user 3 out of 6 (mobilizon_notifs)
Home storage for user mobilizon_notifs not writable
Make sure you're running the scan command only as the user the web server runs as
Starting scan for user 4 out of 6 (user3)
Starting scan for user 5 out of 6 (user4)
Starting scan for user 6 out of 6 (user5)
+---------+-------+--------------+
 ```

### Expected behavior

*I don't want the user mobilizon_notifs have an Nexcloud account, can I remove it from Nextcloud admin ? Or do I have to change the permissions on the Webadmin to excluded this user from Nexctloud ?? I have already excluded the user from the admin in Nextcloud, I am not sure if I can remove it also ?? *

**Comment by yalh76** [comment]
Yes you can remove it from nextcloud.

**Comment by rodinux** [comment]
> Yes you can remove it from nextcloud.

Not really. From the admin in Nextcloud I can't remove it, I haven't the permissions, I just can desactivate this user

**Comment by yalh76** [comment]
ok then, only other option is to wait for "service accounts" to be integrated in YunoHost ... Not for now.
