### ISSUE TITLE
Can't Upgrade to 2.0

### ISSUE THREAD

**Issue by filippodb** [YunoHost-Apps/mobilizon_ynh#124]
### Describe the bug

everything seems to be configured correctly, previous upgrades up to 1.3 went fine but upgrade to 2.0 didn't work. Seems Mobilizon executable hooks into the "wrong port".
Since everything is configured to use port :8097, I don't understand why Mobilizon's "epmd" insists on using port ":4369".

### Context

- Hardware: *VPS bought online 
- YunoHost version: 4.3.5
- I have access to my server: Through SSH
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no

### Expected behavior

Mobilizon to run version 2.0

### Logs

https://paste.yunohost.org/raw/elucexanoc

**Comment by yalh76** [comment]
We can't see anything about `epmd` or `4369` port on your logs

**Comment by yalh76** [comment]
Can you check if you have a file at `/etc/mobilizon/config.exs`

**Comment by filippodb** [comment]
> Can you check if you have a file at `/etc/mobilizon/config.exs`

seems I don't have such file.

Also I tried again to upgrade to 2.0 but failed, I tried to restore the backup but now nobody can login anymore!
I have 800+ users logged out. (before I tried the upgrade on a test server)

**Comment by filippodb** [comment]
> Can you check if you have a file at `/etc/mobilizon/config.exs`

hi, we have updated https://mobilizon.it and we still have the same error.

This is the config on  /etc/mobilizon/config.exs:

`# Mobilizon instance configuration

import Config

config :mobilizon, Mobilizon.Web.Endpoint,
   
   url: [host: "mobilizon.it"],
   http: [
     ip: {0, 0, 0, 0, 0, 0, 0, 1},
     port: 8095
    ],
   secret_key_base: "ADcxtSFbozA5wtVOTJkzU4iQyjkVIHK8vVjWPvJUV3hF8/cknS90Xq71+eLGR2ME"

config :mobilizon, Mobilizon.Web.Auth.Guardian,
  secret_key: "i+p8VvhsO/cpQ1GQQaCXcesK7YPL5hw/a6ONlZK2PXTDGx3rw0ENJjrCREdQ4a4m"

config :mobilizon, :instance,
  name: "Mobilizon",
  description: "Change this to a proper description of your instance",
  hostname: "mobilizon.it",
  registrations_open: false,
  demo: false,
  allow_relay: true,
  federating: true,
  email_from: "mobilizon@mobilizon.it",
  email_reply_to: "mobilizon@mobilizon.it"

config :mobilizon, Mobilizon.Storage.Repo,
  adapter: Ecto.Adapters.Postgres,
  username: "mobilizon",
  password: "Bn38vCiL1gsqyE1TkRDEIincZv5oGL",
  database: "mobilizon",
  hostname: "localhost",
  port: "5432",
  pool_size: 10

config :mobilizon, Mobilizon.Service.Auth.Authenticator, Mobilizon.Service.Auth.LDAPAuthenticator
config :mobilizon, :ldap,
  enabled: true,
  host: "127.0.0.1",
  port: 389,
  ssl: false,
  # sslopts: [],
  tls: false,
  # tlsopts: [],
  base: "ou=users,dc=yunohost,dc=org",
  uid:  "uid",
  require_bind_for_search: false,
  bind_uid: nil,
  bind_password: nil


config :mobilizon, Mobilizon.Web.Email.Mailer,
  adapter: Bamboo.SMTPAdapter,
  server: "127.0.0.1",
  #hostname: "127.0.0.1",
  # usually 25, 465 or 587
  port: 25,
  username: "mobilizon_notifs",
  password: "WRnHJKYPHabHXhSl2HhBoopryPTD0v",
  # can be `:always` or `:never`
  tls: :if_available,
  allowed_tls_versions: [:"tlsv1.2"],
  retries: 1,
  # can be `true`
  no_mx_lookups: false,
  # can be `:always`. If your smtp relay requires authentication set it to `:always`.
  auth: :always


config :mobilizon, Mobilizon.Web.Upload.Uploader.Local, uploads: "/home/yunohost.app/mobilizon/uploads"`
