### ISSUE TITLE
Enhancment: Add application languages in install

### ISSUE THREAD

**Issue by aujawindar** [YunoHost-Apps/mobilizon_ynh#125]
### Describe the bug
When installing apps like Mobilizon, it would be preferable to be able to choose any of the application languages that the app has been translated into. Currently, only French and English are offered, even though many apps (eg. Mobilizon and Mastodon) are translated into numerous languages. 

### Context
All current (Yunohost 4.3.6.2)

### Steps to reproduce
1. Go to Apps -> Install
2. Select an app (for example: Mobilizon)
3. On the app install screen, click on "Choose the application language" dropdown menu

### Expected behavior
When clicking the "Application language" menu, see a list of all languages that the app is translated to. 
The expected result would be the app with the chosen language as default interface language.

**Comment by yalh76** [comment]
Even if the language is asked during install, this parameters is not used ...

**Comment by aujawindar** [comment]
Understood. How do users set application language from now on? In the settings for each application?

**Comment by yalh76** [comment]
I don't know, maybe you should look in the documentation

**Comment by aujawindar** [comment]
There is no Yunohost-specific documentation about this, so there is no function to decide application language in Yunohost at the moment. Thanks for replying and for handling the issue.

**Comment by yalh76** [comment]
In the mobilizon documentation?
