### ISSUE TITLE
E-Mail verification from users without an account doesn't work

### ISSUE THREAD

**Issue by sthaydn** [YunoHost-Apps/mobilizon_ynh#140]
Hi there,

I am on the latest version. I have created an event and sent the link to people without a mobilizon account. They want to take part, but they don't get the verification mail.

Do I need to setup mail manually?

Regards,

Stefan

**Comment by MarinLGU** [comment]
Hello,
I also have an email problem, with a strange error `module Swoosh.Adapters.SMTP is not available`
Full log is available here : https://paste.yunohost.org/xaharabafi
