### ISSUE TITLE
Question about 3.0.1 update ETA

### ISSUE THREAD

**Issue by Szkodnix** [YunoHost-Apps/mobilizon_ynh#152]
Hey there!

I have just a quick question: when can we expect 3.0.1 update for Mobilizon on YunoHost? Do you have any ETA?

Many thanks!

**Comment by isAAAc** [comment]
PR is on the way \o/
https://github.com/YunoHost-Apps/mobilizon_ynh/pull/154

**Comment by yalh76** [comment]
We should wait for 3.0.4 with a working ldap
