### ISSUE TITLE
Install error: `this app must be installed on a domain of its own`

### ISSUE THREAD

**Issue by gordonhjs** [YunoHost-Apps/mobilizon_ynh#160]
### Describe the bug

Impossible to install Mobilizon, error message is `Error: Sorry, this app must be installed on a domain of its own, but other apps are already installed on the domain 'chardon.ynh.fr'. You could use a subdomain dedicated to this app instead.`

### Context

- Hardware: *pi4 at home*
- YunoHost version: 11.1.11.2
- I have access to my server: *Through SSH | through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- Using, or trying to install package version/branch: default

### Steps to reproduce

```sh
   sudo yunohost app install mobilizon
```

### Expected behavior

Mobilizon get installed.

### Logs

Not much logs sadly:

```
$ sudo yunohost app install mobilizon
[sudo] password for admin: 
Choose the domain where this app should be installed [chardon.ynh.fr]: chardon.ynh.fr
Should this app be exposed to anonymous visitors? [yes | no]: yes
Choose the application language [fr | en]: fr
Warning: E-mail turned off for user admin
Choose an administrator user for this app [gordon | admin]: admin
Error: Sorry, this app must be installed on a domain of its own, but other apps are already installed on the domain 'chardon.ynh.fr'. You could use a subdomain dedicated to this app instead.
```

**Comment by yalh76** [comment]
Mobilizon need it's own domain, you should add a new one
