### ISSUE TITLE
Mobilizon 3 is out and stable!!!

### ISSUE THREAD

**Issue by rebelcode-xr** [YunoHost-Apps/mobilizon_ynh#166]
Hi, please could you update to the new major version? 🙏 
https://github.com/framasoft/mobilizon/blob/main/CHANGELOG.md

Latest is `3.1.1` and it seems very stable and more polished, you can test the french instance here: https://mobilizon.fr/
Would help a lot **activists all over the world without tech skills** if you can upgrade this package!

Thank you @yalh76 @rodinux @alexAubin @yunohost-bot @oufmilo @thom4parisot @ericgaspar

**Comment by rodinux** [comment]
Hello, I confirm it works, the PR  #164 is ready to be pushed on testing barnch.
I already test it on an instance... 
With a little change about LDAP I have done but perhaps it is only because of edits I have done before, I explained it on the PR below...

**Comment by rodinux** [comment]
If you don't scare about test it, you can first make a backup and try the upgrade with 
`yunohost app upgrade mobilizon -u https://github.com/YunoHost-Apps/mobilizon_ynh/tree/ci-auto-update-v3.1.1`
Be carefull, I am not really sure nothing will brake (for me I had to change the authentication method), but on a fresh install I have done a test and it works...

**Comment by rebelcode-xr** [comment]
Woow, so fast! I'll inform who manages the server because I'm not dealing with it, thank you! 🎉

**Comment by rodinux** [comment]
Nice, it works with 3.1.3 !

**Comment by rebelcode-xr** [comment]
I can finally confirm: it works! Thank you 🙏
