### ISSUE TITLE
Impossible to login after 2.x to 3.x upgrade.

### ISSUE THREAD

**Issue by filippodb** [YunoHost-Apps/mobilizon_ynh#175]
### Describe the bug

my users can't login anymore.

### Context

- Hardware: *VPS bought online
- YunoHost version:  11.2.4 
- I have access to my server: *Through SSH 
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no 

### Expected behavior

Users should be able to login like dey did on older version.

### Logs

https://paste.yunohost.org/qabehijuho

![image](https://github.com/YunoHost-Apps/mobilizon_ynh/assets/7091176/1db10f06-2541-4ce0-a4f3-1a9edce12cda)

![image](https://github.com/YunoHost-Apps/mobilizon_ynh/assets/7091176/d5fe8d06-5056-45af-a16a-cbfb6b51ebd0)

**Comment by zamentur** [comment]
Have you a log of the upgrade ?

**Comment by isAAAc** [comment]
Hello @zamentur o/
i can't login neither , SSOed or not, 
Installed version: 4.0.2~ynh1

tell me if/how i can help ;) do you prefer i open a new fresh issue ?
i won't be online for the next week,

thx for your help
