### ISSUE TITLE
not sending email after update

### ISSUE THREAD

**Issue by magostinelli** [YunoHost-Apps/mobilizon_ynh#189]
### Describe the bug

Unable to send email

### Context

- Hardware: VPS
- YunoHost: 1.2.10.1
- Mobilizon: 4.0.2~ynh1
- I have access to my server: Through SSH and through the webadmin 

### Steps to reproduce

1. Register to the mobilizon instance
2. Email not delivered
3. Couldn't send an email. Internal error.

### Expected behavior
Sent email

### Logs
Feb 28 19:47:39 yunohost postfix/smtpd[3783555]: warning: TLS library problem: error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../ssl/record/ssl3_record.c:331:
Feb 28 19:47:39 yunohost postfix/smtpd[3783555]: lost connection after STARTTLS from localhost[127.0.0.1]
Feb 28 19:47:39 yunohost postfix/smtpd[3783555]: disconnect from localhost[127.0.0.1] ehlo=1 starttls=0/1 commands=1/2

I tryed to change port from 587 to 25, but i have the same error.

**Comment by magostinelli** [comment]
I found a solution, this is the working configuration:

`
config :mobilizon, Mobilizon.Web.Email.Mailer,
  adapter: Swoosh.Adapters.SMTP,
  relay: "127.0.0.1",
  port: 587,
  username: "mobilizon_notifs",
  password: "mypassword",
  auth: :always,
  ssl: false,
  tls: :always,
  tls_options: [
    versions: [:tlsv1, :"tlsv1.1", :"tlsv1.2",:"tlsv1.3"],
    verify: :verify_peer,
    cacerts: :public_key.cacerts_get(),
    server_name_indication: 'yunohost.server.name',
    depth: 99
  ],
  auth: :always,
  no_mx_lookups: false
`

**Comment by rodinux** [comment]
This is fixed now on last release, thanks for the contribution.
