### ISSUE TITLE
Logging is a bit verbose in syslog

### ISSUE THREAD

**Issue by arthurlogilab** [YunoHost-Apps/mobilizon_ynh#34]
First off, kudos for this packaging ! It helps us deploy and try out mobilizon and get involved in the movement ! 

Looking at the syslog it seems that the application is *very* verbose (logs of SQL queries etc. for example)

**Comment by yalh76** [comment]
Cool, that was the goal ^^

Actual log level is info, that's the default log level

https://github.com/YunoHost-Apps/mobilizon_ynh/blob/cb5393f8a2a59a0dbd69e00761004e0e34b219f8/conf/.env#L14

I haven't found in the wiki or documentation other log level available.... If you find it, I would be pleased to implement or let you do a PR ;)
