### ISSUE TITLE
Remove geolite.maxmind.com

### ISSUE THREAD

**Issue by mediaformat** [YunoHost-Apps/mobilizon_ynh#44]
The subdomain doesn't resolve. 
https://github.com/YunoHost-Apps/mobilizon_ynh/blob/5ba1f12c5781059ecc63025b0266278c24eca465/scripts/install#L191

**Comment by yalh76** [comment]
reported at https://framagit.org/framasoft/mobilizon/issues/340

**Comment by tcitworld** [comment]
Mobilizon doesn't crash anymore if the file is missing, so you can remove this instruction until https://framagit.org/framasoft/mobilizon/issues/340 is fixed.

**Comment by yalh76** [comment]
Thanks a lot @tcitworld ;)
