### ISSUE TITLE
Upgrading seems to have removed a past event 

### ISSUE THREAD

**Issue by arthurlogilab** [YunoHost-Apps/mobilizon_ynh#45]
On https://mobilizon.logilab.fr/ which is deployed using this app (thanks!) I've done the upgrade

Federation works ! I can see my account there from our mastodon instance on https://social.logilab.fr

A past event https://mobilizon.logilab.fr/events/97a72071-f9c8-45e9-b2b5-5e71221b895d has dissapeared though. Is the data supposed to be kept during upgrades ? Or is it because mobilizon archives past events ?

**Comment by yalh76** [comment]
yes data supposed to be kept during upgrades. Did other things disappeared ? like your account in mobilizon?

I don't know if mobilizon archives pasts events. I never used it. Just packaged it because it seems an important project for me.

**Comment by yalh76** [comment]
Without news, I close that issue. Feel free to reopen that issue
