### ISSUE TITLE
installation not succesful because cypress.zip owner is wallabag ?

### ISSUE THREAD

**Issue by nielsh1992** [YunoHost-Apps/mobilizon_ynh#54]
Steps I took:
1) install wallabag via yunohost
2) install mobilizon.

Installation of mobilizon failed because it did not have sufficient acces to /tmp/cypress.zip.
/tmp$ ls -l
-rw-r--r-- 1 wallabag2 wallabag2    9 Mar 19 21:20 cypress.zip

Solved by 
$ sudo chmod 666 cypress.zip
 and restarting the mobilizon installation.

**Comment by yalh76** [comment]
seems that /tmp/cypress.zip owner is wallabag2.
Can you check what is the owner for /tmp ?

**Comment by stemy2** [comment]
Same problem, [here's my log](https://paste.yunohost.org/raw/avukeforaw).

**Comment by yalh76** [comment]
As mobilizon has been fully updated, you should retry to install and let us know if there are still errors
