### ISSUE TITLE
upgrade to 1.0.0-beta.3

### ISSUE THREAD

**Issue by Jaxom99** [YunoHost-Apps/mobilizon_ynh#57]
Hi there,
By any chance, are you looking into upgrading the app to latest version ? 
I'm trying to help Framasoft test the beta...

Thanks for any answer (even negative, I would understand).

**Comment by yalh76** [comment]
I didn't see that there was a 1.0.0-beta.3, just added in my long todo list ^^

**Comment by alexAubin** [comment]
Testing got upgraded to 1.0.0 rc1

c.f. the instructions in the readme, it can be tested using : 

```
sudo yunohost app install https://github.com/YunoHost-Apps/mobilizon_ynh/tree/testing
sudo yunohost app upgrade mobilizon -u https://github.com/YunoHost-Apps/mobilizon_ynh/tree/testing
```
