### ISSUE TITLE
[stretch -> buster] postgis migration seems to be problematic

### ISSUE THREAD

**Issue by arthurlogilab** [YunoHost-Apps/mobilizon_ynh#59]
On an internal test instance install of mobilizon we've had a problem when migrating to buster using the yunohost migration scripts. 

The logs and debug steps are detailed on the forum : https://forum.yunohost.org/t/stretch-buster-probleme-de-migration-postgresql/12332/3 

Not sure how this can be fixed properly.

**Comment by yalh76** [comment]
Maybe the issue should be open at https://github.com/YunoHost/issues/issues, It's more related to YunoHost migraiton than mobilizon only ^^

**Comment by yalh76** [comment]
https://github.com/YunoHost-Apps/mobilizon_ynh/commit/4d35cfa0e4044254cfd1c3959dacb47dd83646c7 should solve that problem.
