### ISSUE TITLE
no page loading for install on root

### ISSUE THREAD

**Issue by Gredin67** [YunoHost-Apps/mobilizon_ynh#61]
Hi, I installed mobilizon branch [1.0.0 beta3] successfully on social.domain.ltd (domain root) . The service is running and getting
`oct. 12 20:00:34 mobilizon[1291]: 20:00:34.875 request_id=Fj1QkwovrC-_2-sAAAWC [info] GET /sitemap.xml`

But now no page is loading. Could it be that the installation on root is not working properly?

**Comment by alexAubin** [comment]
Got fixed yesterday
