### ISSUE TITLE
LDAP is not working

### ISSUE THREAD

**Issue by stemy2** [YunoHost-Apps/mobilizon_ynh#68]
### Describe the bug

During install, i had to define an administrator, but i can't connect with my account, wich is not found.

### Context

- Hardware: *Desktop PC*
- YunoHost version: 4.0.8
- I have access to my server: *Full*
- Using, or trying to install package version/branch: Master

### Steps to reproduce

- *If you performed a command from the CLI, the command itself is enough.
   
   1. *Install the app*
   2. *Set yourself as admin*
   3. *Try to login*

### Expected behavior

*Since LDAP is showed as working, i should be able to login directly.*

**Comment by stemy2** [comment]
I'm already have the version 1.0.0. The installer just asked me to set the administrator username, nothing else.

**Comment by yalh76** [comment]
you must use the yunohost email and password of the user you choose during install.

**Comment by stemy2** [comment]
As i said, i could not at any time choose an email/password during install, the installer just asked me the YNH username of the admin.

**Comment by yalh76** [comment]
you choose a YunoHost user during install....

This YunoHost user has an email address and a password...

use them.

**Comment by stemy2** [comment]
> you choose a YunoHost user during install....
> 
> This YunoHost user has an email address and a password...
> 
> use them.

This is exactly what i did, and the instance said "user doesn't exist".
