### ISSUE TITLE
login button and /login don't work

### ISSUE THREAD

**Issue by deckname** [YunoHost-Apps/mobilizon_ynh#69]
### Describe the bug

When I click on mobilizon.domain.tld the site loads fine. But clicking on Log in doesn't load the login site. Going to /login doesn't load anything.
This is the behavior after a reinstall on the same domain, before I could load the /login page but it didn't allow me to login with admin user e-mail and pw. 
This is only the case when I am logged in on yunohost SSO. 

### Context

- Hardware: VPS
- YunoHost version: 4.0.8
- I have access to my server: all of the access
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance ?: no
- Using, or trying to install package version/branch: 1.0.0

### How to fix this
How I fixed this on my install? On nginx /etc/nginx/conf.d/mobilizon.domain.tld.conf I commented out the line `access_by_lua_file /usr/share/ssowat/access.lua;` from both 80 and 443 config. 
Apparently yunohost SSO was conflicting with

**Comment by yalh76** [comment]
It seem weird because I tested several time in the same conditions without having that issue... Well at least YunoHost 4.1 and the new permission system can solve that

**Comment by maniackcrudelis** [comment]
Hi

I confirm the issue, only when connected to the SSO.
There's a conflict between the SSO and mobilizon.

Here's the error shown by mobilizon:

```
Error: You need to be logged in

e@https://domain.tld/js/chunk-vendors.b1d11b09.js:16:116446
2723/L</t.prototype.getResultsFromLink/<@https://domain.tld/js/chunk-vendors.b1d11b09.js:16:97324
n@https://domain.tld/js/chunk-vendors.b1d11b09.js:16:78816
then/<@https://domain.tld/js/chunk-vendors.b1d11b09.js:16:78741
then@https://domain.tld/js/chunk-vendors.b1d11b09.js:16:78707
l/<@https://domain.tld/js/chunk-vendors.b1d11b09.js:16:78826
g@https://domain.tld/js/chunk-vendors.b1d11b09.js:31:3962
w@https://domain.tld/js/chunk-vendors.b1d11b09.js:31:4330
value@https://domain.tld/js/chunk-vendors.b1d11b09.js:31:4884
i/<@https://domain.tld/js/chunk-vendors.b1d11b09.js:31:20213
i@https://domain.tld/js/chunk-vendors.b1d11b09.js:31:20181
next@https://domain.tld/js/chunk-vendors.b1d11b09.js:16:77121
g@https://domain.tld/js/chunk-vendors.b1d11b09.js:31:3962
w@https://domain.tld/js/chunk-vendors.b1d11b09.js:31:4330
value@https://domain.tld/js/chunk-vendors.b1d11b09.js:31:4884
next@https://domain.tld/js/chunk-vendors.b1d11b09.js:16:119897
g@https://domain.tld/js/chunk-vendors.b1d11b09.js:31:3962
w@https://domain.tld/js/chunk-vendors.b1d11b09.js:31:4330
value@https://domain.tld/js/chunk-vendors.b1d11b09.js:31:4884
m/</</<@https://domain.tld/js/chunk-vendors.b1d11b09.js:16:122516
```

Thanks to @deckname for the solution that indeed solve the problem.
