### ISSUE TITLE
Error: Pick a valid value for the argument 'domain': Unknown domain

### ISSUE THREAD

**Issue by RayBB** [YunoHost-Apps/mobilizon_ynh#70]
### Describe the bug
When trying to setup the app in the admin UI I get the errror:
`Pick a valid value for the argument 'domain': Unknown domain`

The domain for my yunohost instance is like: mysubdomain.nohost.me
For the field `Choose a domain name for Mobilizon`
I entered `events.mysubdomain.nohost.me`
However, it gives me the error mentioned above.

I feel like this may not even be a bug but I'm just not sure what I am doing wrong.

### Context

- Hardware: VPS
- YunoHost version: 4.0.8.2 (stable)
- I have access to my server: using webadmin but can ssh too.
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance ?: no
- Using, or trying to install package version/branch: just pasting https://github.com/YunoHost-Apps/mobilizon_ynh/ in custom

### Steps to reproduce

1. on your yunohost instance paste `https://github.com/YunoHost-Apps/mobilizon_ynh/` in the Install custom app field.
2. click install
3. add domain as described above, select en, enter a user name
4. click install

### Logs

From what I can tell there was no link to logs just a pin/dismiss button near notification.

**Comment by RayBB** [comment]
For some reason I wasn't seeing this app in the app catalogue but now I am.

However, when installing from there I get the error `Sorry, this app must be installed on a domain of its own, but other apps are already installed on the domain 'mysubdomain.nohost.me'. You could use a subdomain dedicated to this app instead.`

# Resolution
1. Add a new subdomain from a domain I actually own
2. Pick the new domain added during setup


So it seems that to install this app we must have our own domain/subdomain?

**Comment by anmol26s** [comment]
Yes this app required a domain of its own.
Please read this https://github.com/YunoHost-Apps/mobilizon_ynh/#important-points-to-read-before-installing

**Comment by RayBB** [comment]
Thank you for the clarification. I'm new to yunohost and mobilizon so I just missed this readme note somehow.

This is a great project I appreciate you setting it up :)
