### ISSUE TITLE
Issue when installing Mobilizon

### ISSUE THREAD

**Issue by fheslouin** [YunoHost-Apps/mobilizon_ynh#71]
### Describe the bug

Issue when installing Mobilizon, dependency errors 

### Context

- Hardware: *VPS bought online*
- YunoHost version: 4.0.8.2
- I have access to my server: *Through SSH*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance ?: *no*

### Steps to reproduce

- *If you performed a command from the CLI, the command itself is enough. For example:*
    ```sh
    sudo yunohost app install mobilizon
    ```
### Expected behavior

Mobilizon should be installed

### Logs

https://paste.yunohost.org/raw/ucuragayaw

**Comment by oncletom** [comment]
To follow up on this, @fheslouin reported a conflict with the OnlyOffice app. Both cannot be installed at the same time, for a reason I'm not aware of.

Is it because OnlyOffice uses a different elixir setup?

**Comment by TROMsite** [comment]
I cannot install on my end either. Full logs here https://paste.yunohost.org/raw/qarokilegi

**Comment by yalh76** [comment]
> 
> 
> I cannot install on my end either. Full logs here https://paste.yunohost.org/raw/qarokilegi

It seems that you have a conflict for `erlang-base : Conflicts: erlang-base-hipe` what other app have you on your YunoHost ?

**Comment by TROMsite** [comment]
A few: peertube, friendica, nextcloud, searx, lufi, etherpad, diagrams, rss-bridge, framadate, libre qr, bibliogram and invidious.

**Comment by TROMsite** [comment]
Hi. Any updates on this? I am still unable to install Mobilizon. 
```
Unable to install mobilizon: An error occurred inside the app installation script

Unable to install dependencies

Recommends: erlang-mode but it is not going to be installed

Conflicts: erlang-xmerl

Conflicts: erlang-tools

Conflicts: erlang-syntax-tools

Conflicts: erlang-ssl

Conflicts: erlang-snmp

Conflicts: erlang-runtime-tools

Conflicts: erlang-public-key

Conflicts: erlang-parsetools

Conflicts: erlang-os-mon

Conflicts: erlang-mnesia

Conflicts: erlang-inets

Conflicts: erlang-crypto

Conflicts: erlang-asn1

Conflicts: erlang-base but 1:23.3.1-1 is to be installed

Depends: libsctp1 but it is not going to be installed

libwxgtk3.0-gtk3-0v5 but it is not going to be installed

libwxgtk3.0-0v5 but it is not going to be installed or

libwxgtk3.0-0 but it is not installable or

Depends: libwxgtk2.8-0 but it is not installable or

libwxbase3.0-0v5 but it is not going to be installed

libwxbase3.0-0 but it is not installable or

Depends: libwxbase2.8-0 but it is not installable or

esl-erlang : Depends: libncurses5 but it is not going to be installed

erlang-base : Conflicts: erlang-base-hipe

The following packages have unmet dependencies:

E: Packages need to be removed but remove is disabled.
```
