### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by rsheftel** [YunoHost-Apps/mobilizon_ynh#78]
I am using Yunohost installed from January 15, 2021 on a cloud VPS. I have installed (and they are working) RoundCube and Freindica. When I go to install Mobilizon I get the following error log.

I used the web UI to do the installation, and it is from the main branch

Debug log: https://paste.yunohost.org/raw/amudirojig

**Comment by tiotrom** [comment]
Same here. It fails. I have over 20 apps installed. All work. But this one fails https://paste.yunohost.org/raw/satuwikute

**Comment by stemy2** [comment]
Same here.
https://paste.yunohost.org/raw/mocuvozote

**Comment by yalh76** [comment]
Found why => https://framacolibri.org/t/solved-recuperation-des-dependances-elixir-hs/10927/17.
caused by a rebase, commits have been rewrite and actual and previous version won't more install
We will need to wait next release

**Comment by stemy2** [comment]
Hello, could you reopen the issue ? It keeps failing at my side.

https://paste.yunohost.org/raw/wuhesenita
