### ISSUE TITLE
Do we still need erlang+local build now that we're in 1.1.0 ?

### ISSUE THREAD

**Issue by alexAubin** [YunoHost-Apps/mobilizon_ynh#90]
Just realized that the package got bumped to 1.1.0, thank you so much @yalh76 <3

Supposedly in 1.1.0, mobilizon provides already-build archives, so erlang + the build step shouldn't be needed anymore, which would greatly speed up the install and simplify the whole package (+ remove weird conflicts with onlyoffice because of rabbitmq/erland).

Did any body have a look into this ?

**Comment by yalh76** [comment]
I've look at it but there is only x64 build... I've opened an issue if they can provide builds for other architecture as they use gitlab like pleroma....

**Comment by tcitworld** [comment]
`arm` and `arm64` are now prebuilt as well https://framagit.org/framasoft/mobilizon/-/releases/2.0.0

**Comment by alexAubin** [comment]
Thank you so much <3
