### ISSUE TITLE
we can't upload images because /var/lib/mobilizon/uploads folder does not exists

### ISSUE THREAD

**Issue by filippodb** [YunoHost-Apps/mobilizon_ynh#92]
### Describe the bug

mobilizon install failed

### Context

- Hardware: VPS bought online 8GB RAM, 200GBSSD
- YunoHost version: 4.1.8
- I have access to my server: Through SSH | through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no, fresh install

### Expected behavior

mobilizon installed

### Logs

https://paste.yunohost.org/raw/wigorisove

**Comment by yalh76** [comment]
Seems that your YunoHost can't start a listener on port 8095.

Do you have other apps installed ?

**Comment by filippodb** [comment]
> Seems that your YunoHost can't start a listener on port 8095.
> 
> Do you have other apps installed ?

seems the server didn't have ipv6 activated. 
I reinstalled and it's working: https://mobilizon.it 
this is the new installation log:

https://paste.yunohost.org/raw/xajuwaxine

the registrations are working but we can't upload images and can't even create events! 

It's a fresh install not a single other app is installed.

**Comment by yalh76** [comment]
>  and can't even create events!

You should look at mobilizon logs when trying to create events or uploading files to see what's happen

**Comment by filippodb** [comment]
![image](https://user-images.githubusercontent.com/7091176/115848100-cd4b3200-a423-11eb-96fc-33d46e22b751.png)
seems folder  /var/lib/mobilizon/ not exist.
yunohost does not create it, it create another folder here: ./var/www/mobilizon/mobilizon/uploads

![image](https://user-images.githubusercontent.com/7091176/115848141-db00b780-a423-11eb-946d-d240d37b14be.png)

seems an installation bug.

**Comment by filippodb** [comment]
seems we can't upload images because /var/lib/mobilizon/uploads folder does not exists:
![image](https://user-images.githubusercontent.com/7091176/115849371-1b146a00-a425-11eb-9c59-8b9b626cfd94.png)

seems yunost is creating an upload folder on a wrong place: ./var/www/mobilizon/mobilizon/uploads
![image](https://user-images.githubusercontent.com/7091176/115849730-76465c80-a425-11eb-9afa-6169f7cd3c2a.png)
