### ISSUE TITLE
text error in confirmation email

### ISSUE THREAD

**Issue by filippodb** [YunoHost-Apps/mobilizon_ynh#96]
the confirmation emails don't show the host name but it show:  % {host}

![image](https://user-images.githubusercontent.com/7091176/115966567-7ed68a00-a52e-11eb-9db9-cc203a57cb21.png)

**Comment by yalh76** [comment]
Tested on two instances...

![image](https://user-images.githubusercontent.com/30271971/116695465-f427dc00-a9c0-11eb-8cf0-7a467c7af815.png)

Maybe you should look at `/var/www/mobilizon/mobilizon/config/prod.secret.exs`

**Comment by cescobarresi** [comment]
There is a typo in the translation: a space between the "%" and the "{".

This are the lines with the errors:
`
it/LC_MESSAGES/default.po:641:"di <b>% {instance_name} </b> del sito. L'utilizzo di tali siti Web collegati "
it/LC_MESSAGES/default.po:668:"{instance_name} </b> (<a href=\"https://%{instance_url}\">% {instance_url} "
it/LC_MESSAGES/default.po:720:"sostituendo qualsiasi accordo precedente tra te e <b>% {instance_name} </b> "
it/LC_MESSAGES/default.po:873:"Devi rispettare le altre persone e le regole di <b>% {instance_name} </b> "
it/LC_MESSAGES/default.po:880:msgstr "Devi rispettare la legge quando utilizzi <b>% {instance_name} </b>"
it/LC_MESSAGES/default.po:903:"Ciao! Ti sei appena registrato per partecipare a questo evento: «% {title}». "
it/LC_MESSAGES/default.po:916:"Hai creato un account su <b>% {host} </b> con questo indirizzo email. Sei a "
it/LC_MESSAGES/default.po:928:"L'indirizzo email del tuo account su <b>% {host} </b> verrà modificato in:"
it/LC_MESSAGES/default.po:934:"Hai richiesto una nuova password per il tuo account su <b>% {instance} </b>."
it/LC_MESSAGES/default.po:970:msgstr "% {instance} è alimentata da Mobilizon."
it/LC_MESSAGES/default.po:1031:"account su <b>% {instance} </b>. Se desideri ancora farlo, fai clic sul "
it/LC_MESSAGES/default.po:1040:"tuo account su% {host} è stato cambiato da questo a:"
it/LC_MESSAGES/default.po:1048:"abbia ottenuto l'accesso al tuo account% {host}. Effettua il login e "
it/LC_MESSAGES/default.po:1050:"l'amministratore su% {host}."
it/LC_MESSAGES/default.po:1116:"Qualcuno su <b>% {instance} </b> ha segnalato i seguenti contenuti da "
it/LC_MESSAGES/default.po:1198:msgstr "Visita la pagina dell'evento aggiornata:% {link}"
`

Where should we let this be known?
Thanks.

Francesco

**Comment by yalh76** [comment]
> 
> Where should we let this be known?
> Thanks.
> 
> Francesco

You should open an issue in the uptrseam app repository
