### ISSUE TITLE
Installation Fails with no other apps installed

### ISSUE THREAD

**Issue by torpherson** [YunoHost-Apps/mobilizon_ynh#99]
### Describe the bug

Installation Fails on an up to date Debian 10 vps with no other apps installed.  

### Context

- Hardware: VPS bought online
- YunoHost version: YunoHost 4.1.8 
- I have access to my server: Through SSH | through the webadmin 
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using, or trying to install package version/branch: mobilizon

### Steps to reproduce

    ```sh
    sudo yunohost app install mobilizon
    ```
### Expected behavior

instillation fails

### Logs

https://paste.yunohost.org/raw/umokudepow

**Comment by yalh76** [comment]
Seems like a random nodejs error ...
You should check the size available on your VPS and retry to install
